// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/accountpb/account.proto

package accountpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance              int64    `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_eda8513f7b6ec391, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type CreateAccountRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eda8513f7b6ec391, []int{1}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eda8513f7b6ec391, []int{2}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateAccountOwnerRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountOwnerRequest) Reset()         { *m = UpdateAccountOwnerRequest{} }
func (m *UpdateAccountOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountOwnerRequest) ProtoMessage()    {}
func (*UpdateAccountOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eda8513f7b6ec391, []int{3}
}

func (m *UpdateAccountOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountOwnerRequest.Unmarshal(m, b)
}
func (m *UpdateAccountOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountOwnerRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountOwnerRequest.Merge(m, src)
}
func (m *UpdateAccountOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountOwnerRequest.Size(m)
}
func (m *UpdateAccountOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountOwnerRequest proto.InternalMessageInfo

func (m *UpdateAccountOwnerRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdateAccountOwnerRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type UpdateAccountOwnerResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountOwnerResponse) Reset()         { *m = UpdateAccountOwnerResponse{} }
func (m *UpdateAccountOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountOwnerResponse) ProtoMessage()    {}
func (*UpdateAccountOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eda8513f7b6ec391, []int{4}
}

func (m *UpdateAccountOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountOwnerResponse.Unmarshal(m, b)
}
func (m *UpdateAccountOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountOwnerResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccountOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountOwnerResponse.Merge(m, src)
}
func (m *UpdateAccountOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountOwnerResponse.Size(m)
}
func (m *UpdateAccountOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountOwnerResponse proto.InternalMessageInfo

func (m *UpdateAccountOwnerResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateAccountBalanceRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TransactionType      string   `protobuf:"bytes,2,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountBalanceRequest) Reset()         { *m = UpdateAccountBalanceRequest{} }
func (m *UpdateAccountBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountBalanceRequest) ProtoMessage()    {}
func (*UpdateAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eda8513f7b6ec391, []int{5}
}

func (m *UpdateAccountBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountBalanceRequest.Unmarshal(m, b)
}
func (m *UpdateAccountBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountBalanceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountBalanceRequest.Merge(m, src)
}
func (m *UpdateAccountBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountBalanceRequest.Size(m)
}
func (m *UpdateAccountBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountBalanceRequest proto.InternalMessageInfo

func (m *UpdateAccountBalanceRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdateAccountBalanceRequest) GetTransactionType() string {
	if m != nil {
		return m.TransactionType
	}
	return ""
}

func (m *UpdateAccountBalanceRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type UpdateAccountBalanceResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountBalanceResponse) Reset()         { *m = UpdateAccountBalanceResponse{} }
func (m *UpdateAccountBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountBalanceResponse) ProtoMessage()    {}
func (*UpdateAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eda8513f7b6ec391, []int{6}
}

func (m *UpdateAccountBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountBalanceResponse.Unmarshal(m, b)
}
func (m *UpdateAccountBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountBalanceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccountBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountBalanceResponse.Merge(m, src)
}
func (m *UpdateAccountBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountBalanceResponse.Size(m)
}
func (m *UpdateAccountBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountBalanceResponse proto.InternalMessageInfo

func (m *UpdateAccountBalanceResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*CreateAccountRequest)(nil), "account.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "account.CreateAccountResponse")
	proto.RegisterType((*UpdateAccountOwnerRequest)(nil), "account.UpdateAccountOwnerRequest")
	proto.RegisterType((*UpdateAccountOwnerResponse)(nil), "account.UpdateAccountOwnerResponse")
	proto.RegisterType((*UpdateAccountBalanceRequest)(nil), "account.UpdateAccountBalanceRequest")
	proto.RegisterType((*UpdateAccountBalanceResponse)(nil), "account.UpdateAccountBalanceResponse")
}

func init() { proto.RegisterFile("account/accountpb/account.proto", fileDescriptor_eda8513f7b6ec391) }

var fileDescriptor_eda8513f7b6ec391 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x4e, 0xb3, 0x40,
	0x10, 0xc7, 0x03, 0xcd, 0x57, 0xc2, 0x34, 0x5f, 0x6d, 0x36, 0x68, 0x10, 0xad, 0x36, 0xa8, 0x49,
	0xf5, 0x50, 0x93, 0xfa, 0x04, 0xd2, 0x8b, 0xf5, 0xa0, 0x06, 0xf5, 0x62, 0x62, 0x9a, 0x65, 0xd9,
	0x03, 0x89, 0xee, 0xae, 0xb0, 0xd5, 0xf4, 0xe4, 0xcb, 0xf8, 0xa0, 0x46, 0xd8, 0x45, 0x51, 0x50,
	0xeb, 0x89, 0x9d, 0x61, 0xe6, 0xbf, 0xbf, 0x99, 0xd9, 0x81, 0x6d, 0x4c, 0x08, 0x9f, 0x33, 0x79,
	0xa8, 0xbe, 0x22, 0xd2, 0xa7, 0x91, 0x48, 0xb9, 0xe4, 0xc8, 0x52, 0xa6, 0x3f, 0x05, 0xeb, 0xb8,
	0x38, 0xa2, 0x2e, 0x98, 0x49, 0xec, 0x1a, 0x03, 0x63, 0x68, 0x87, 0x66, 0x12, 0x23, 0x07, 0xfe,
	0xf1, 0x27, 0x46, 0x53, 0xd7, 0xcc, 0x5d, 0x85, 0x81, 0x5c, 0xb0, 0x22, 0x7c, 0x87, 0x19, 0xa1,
	0x6e, 0x6b, 0x60, 0x0c, 0x5b, 0xa1, 0x36, 0xfd, 0x00, 0x9c, 0x49, 0x4a, 0xb1, 0xa4, 0x4a, 0x30,
	0xa4, 0x0f, 0x73, 0x9a, 0x49, 0x74, 0x00, 0xfa, 0xb6, 0x5c, 0xbc, 0x33, 0xee, 0x8d, 0x34, 0x8c,
	0x8e, 0x2c, 0x71, 0x26, 0xb0, 0xfa, 0x49, 0x23, 0x13, 0x9c, 0x65, 0x74, 0x29, 0x91, 0x0b, 0x58,
	0xbf, 0x16, 0xf1, 0xbb, 0xc8, 0xf9, 0x1b, 0xb8, 0xa6, 0xe9, 0x03, 0xa8, 0xb8, 0x59, 0x59, 0xad,
	0xad, 0x3c, 0xd3, 0x86, 0xa2, 0xfd, 0x13, 0xf0, 0xea, 0x14, 0xff, 0xc0, 0xf6, 0x0c, 0x1b, 0x15,
	0xa5, 0xa0, 0x68, 0xde, 0x2f, 0xe9, 0xf6, 0xa1, 0x27, 0x53, 0xcc, 0x32, 0x4c, 0x64, 0xc2, 0xd9,
	0x4c, 0x2e, 0x04, 0x55, 0xa0, 0x2b, 0x1f, 0xfc, 0x57, 0x0b, 0x41, 0xd1, 0x1a, 0xb4, 0xf1, 0x7d,
	0xce, 0x54, 0x8c, 0x49, 0x59, 0xfe, 0x29, 0x6c, 0xd6, 0x03, 0x2c, 0x5f, 0xcc, 0xf8, 0xc5, 0x84,
	0xae, 0x72, 0x5e, 0xd2, 0xf4, 0x31, 0x21, 0x14, 0x9d, 0xc1, 0xff, 0xca, 0x00, 0x51, 0xbf, 0x4c,
	0xaf, 0x7b, 0x1c, 0xde, 0x56, 0xd3, 0x6f, 0x85, 0x73, 0x0b, 0xe8, 0x6b, 0xe7, 0x91, 0x5f, 0x66,
	0x35, 0x0e, 0xda, 0xdb, 0xf9, 0x36, 0x46, 0xc9, 0x13, 0x70, 0xea, 0xba, 0x81, 0x76, 0xeb, 0x93,
	0xab, 0xd3, 0xf2, 0xf6, 0x7e, 0x88, 0x2a, 0x2e, 0x09, 0x3a, 0x37, 0x76, 0xb9, 0x87, 0x51, 0x3b,
	0x5f, 0xc0, 0xa3, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x83, 0xd4, 0xac, 0xa3, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	UpdateAccountOwner(ctx context.Context, in *UpdateAccountOwnerRequest, opts ...grpc.CallOption) (*UpdateAccountOwnerResponse, error)
	UpdateAccountBalance(ctx context.Context, in *UpdateAccountBalanceRequest, opts ...grpc.CallOption) (*UpdateAccountBalanceResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateAccountOwner(ctx context.Context, in *UpdateAccountOwnerRequest, opts ...grpc.CallOption) (*UpdateAccountOwnerResponse, error) {
	out := new(UpdateAccountOwnerResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/UpdateAccountOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateAccountBalance(ctx context.Context, in *UpdateAccountBalanceRequest, opts ...grpc.CallOption) (*UpdateAccountBalanceResponse, error) {
	out := new(UpdateAccountBalanceResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/UpdateAccountBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	UpdateAccountOwner(context.Context, *UpdateAccountOwnerRequest) (*UpdateAccountOwnerResponse, error)
	UpdateAccountBalance(context.Context, *UpdateAccountBalanceRequest) (*UpdateAccountBalanceResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedAccountServiceServer) UpdateAccountOwner(ctx context.Context, req *UpdateAccountOwnerRequest) (*UpdateAccountOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccountOwner not implemented")
}
func (*UnimplementedAccountServiceServer) UpdateAccountBalance(ctx context.Context, req *UpdateAccountBalanceRequest) (*UpdateAccountBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccountBalance not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateAccountOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateAccountOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/UpdateAccountOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateAccountOwner(ctx, req.(*UpdateAccountOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateAccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateAccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/UpdateAccountBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateAccountBalance(ctx, req.(*UpdateAccountBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
		{
			MethodName: "UpdateAccountOwner",
			Handler:    _AccountService_UpdateAccountOwner_Handler,
		},
		{
			MethodName: "UpdateAccountBalance",
			Handler:    _AccountService_UpdateAccountBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/accountpb/account.proto",
}
